server:
  port: 8081
  servlet:
    context-path: /quartz
spring:
  quartz:
    auto-startup: true
    scheduler-name: quartzScheduler
    jdbc:
      comment-prefix: "#"
      initialize-schema: never
    job-store-type: jdbc
    overwrite-existing-jobs: true
    wait-for-jobs-to-complete-on-shutdown: true
    properties:
      org.quartz.jobStore.class: org.quartz.impl.jdbcjobstore.JobStoreTX
      org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
      org.quartz.jobStore.dataSource: quartzDataSource
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/quartz_db
    username: root
    password: 123456
